// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin 0.7.0
// 	protoc               v3.20.1
// source: krpc_meta.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KrpcMeta_Direction int32

const (
	KrpcMeta_INVALID_DIRECTION KrpcMeta_Direction = 0
	KrpcMeta_REQUEST           KrpcMeta_Direction = 1
	KrpcMeta_RESPONSE          KrpcMeta_Direction = 2
)

// Enum value maps for KrpcMeta_Direction.
var (
	KrpcMeta_Direction_name = map[int32]string{
		0: "INVALID_DIRECTION",
		1: "REQUEST",
		2: "RESPONSE",
	}
	KrpcMeta_Direction_value = map[string]int32{
		"INVALID_DIRECTION": 0,
		"REQUEST":           1,
		"RESPONSE":          2,
	}
)

func (x KrpcMeta_Direction) Enum() *KrpcMeta_Direction {
	p := new(KrpcMeta_Direction)
	*p = x
	return p
}

type KrpcMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direction KrpcMeta_Direction `protobuf:"varint,1,opt,name=direction,proto3,enum=ProtobufRpc.KrpcMeta_Direction" json:"direction,omitempty"`
	ServiceId int32              `protobuf:"varint,2,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	MsgId     int32              `protobuf:"varint,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Sequence  int32              `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	RetCode   int32              `protobuf:"varint,6,opt,name=retCode,proto3" json:"retCode,omitempty"`
	Trace     *KrpcMeta_Trace    `protobuf:"bytes,7,opt,name=trace,proto3" json:"trace,omitempty"`
}

func (x *KrpcMeta) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *KrpcMeta) GetDirection() KrpcMeta_Direction {
	if x != nil {
		return x.Direction
	}
	return KrpcMeta_INVALID_DIRECTION
}

func (x *KrpcMeta) GetServiceId() int32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *KrpcMeta) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *KrpcMeta) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *KrpcMeta) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

func (x *KrpcMeta) GetTrace() *KrpcMeta_Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

type KrpcMeta_Trace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceId      string `protobuf:"bytes,2,opt,name=traceId,proto3" json:"traceId,omitempty"`
	ParentSpanId string `protobuf:"bytes,3,opt,name=parentSpanId,proto3" json:"parentSpanId,omitempty"`
	SpanId       string `protobuf:"bytes,4,opt,name=spanId,proto3" json:"spanId,omitempty"`
}

func (x *KrpcMeta_Trace) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *KrpcMeta_Trace) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *KrpcMeta_Trace) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *KrpcMeta_Trace) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}
