// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.6
// source: WasmPluginApi.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppRespStatus int32

const (
	AppRespStatus_RESP_OK           AppRespStatus = 0
	AppRespStatus_RESP_TIMEOUT      AppRespStatus = 2
	AppRespStatus_RESP_SERVER_ERROR AppRespStatus = 3
	AppRespStatus_RESP_CLIENT_ERROR AppRespStatus = 4
	AppRespStatus_RESP_UNKNOWN      AppRespStatus = 5
)

// Enum value maps for AppRespStatus.
var (
	AppRespStatus_name = map[int32]string{
		0: "RESP_OK",
		2: "RESP_TIMEOUT",
		3: "RESP_SERVER_ERROR",
		4: "RESP_CLIENT_ERROR",
		5: "RESP_UNKNOWN",
	}
	AppRespStatus_value = map[string]int32{
		"RESP_OK":           0,
		"RESP_TIMEOUT":      2,
		"RESP_SERVER_ERROR": 3,
		"RESP_CLIENT_ERROR": 4,
		"RESP_UNKNOWN":      5,
	}
)

func (x AppRespStatus) Enum() *AppRespStatus {
	p := new(AppRespStatus)
	*p = x
	return p
}

func (x AppRespStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppRespStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_WasmPluginApi_proto_enumTypes[0].Descriptor()
}

func (AppRespStatus) Type() protoreflect.EnumType {
	return &file_WasmPluginApi_proto_enumTypes[0]
}

func (x AppRespStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppRespStatus.Descriptor instead.
func (AppRespStatus) EnumDescriptor() ([]byte, []int) {
	return file_WasmPluginApi_proto_rawDescGZIP(), []int{0}
}

type AppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *string                `protobuf:"bytes,1,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Type          *string                `protobuf:"bytes,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Domain        *string                `protobuf:"bytes,3,opt,name=domain,proto3,oneof" json:"domain,omitempty"`
	Resource      *string                `protobuf:"bytes,4,opt,name=resource,proto3,oneof" json:"resource,omitempty"`
	Endpoint      *string                `protobuf:"bytes,5,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppRequest) Reset() {
	*x = AppRequest{}
	mi := &file_WasmPluginApi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppRequest) ProtoMessage() {}

func (x *AppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_WasmPluginApi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppRequest.ProtoReflect.Descriptor instead.
func (*AppRequest) Descriptor() ([]byte, []int) {
	return file_WasmPluginApi_proto_rawDescGZIP(), []int{0}
}

func (x *AppRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *AppRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *AppRequest) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

func (x *AppRequest) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *AppRequest) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

type AppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *AppRespStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=wasm_plugin.AppRespStatus,oneof" json:"status,omitempty"`
	Code          *int32                 `protobuf:"varint,2,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Exception     *string                `protobuf:"bytes,3,opt,name=exception,proto3,oneof" json:"exception,omitempty"`
	Result        *string                `protobuf:"bytes,4,opt,name=result,proto3,oneof" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppResponse) Reset() {
	*x = AppResponse{}
	mi := &file_WasmPluginApi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppResponse) ProtoMessage() {}

func (x *AppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_WasmPluginApi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppResponse.ProtoReflect.Descriptor instead.
func (*AppResponse) Descriptor() ([]byte, []int) {
	return file_WasmPluginApi_proto_rawDescGZIP(), []int{1}
}

func (x *AppResponse) GetStatus() AppRespStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return AppRespStatus_RESP_OK
}

func (x *AppResponse) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *AppResponse) GetException() string {
	if x != nil && x.Exception != nil {
		return *x.Exception
	}
	return ""
}

func (x *AppResponse) GetResult() string {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ""
}

type AppTrace struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TraceId         *string                `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3,oneof" json:"trace_id,omitempty"`
	SpanId          *string                `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3,oneof" json:"span_id,omitempty"`
	ParentSpanId    *string                `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3,oneof" json:"parent_span_id,omitempty"`
	XRequestId      *string                `protobuf:"bytes,4,opt,name=x_request_id,json=xRequestId,proto3,oneof" json:"x_request_id,omitempty"`
	HttpProxyClient *string                `protobuf:"bytes,5,opt,name=http_proxy_client,json=httpProxyClient,proto3,oneof" json:"http_proxy_client,omitempty"`
	TraceIds        []string               `protobuf:"bytes,6,rep,name=trace_ids,json=traceIds,proto3" json:"trace_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AppTrace) Reset() {
	*x = AppTrace{}
	mi := &file_WasmPluginApi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppTrace) ProtoMessage() {}

func (x *AppTrace) ProtoReflect() protoreflect.Message {
	mi := &file_WasmPluginApi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppTrace.ProtoReflect.Descriptor instead.
func (*AppTrace) Descriptor() ([]byte, []int) {
	return file_WasmPluginApi_proto_rawDescGZIP(), []int{2}
}

func (x *AppTrace) GetTraceId() string {
	if x != nil && x.TraceId != nil {
		return *x.TraceId
	}
	return ""
}

func (x *AppTrace) GetSpanId() string {
	if x != nil && x.SpanId != nil {
		return *x.SpanId
	}
	return ""
}

func (x *AppTrace) GetParentSpanId() string {
	if x != nil && x.ParentSpanId != nil {
		return *x.ParentSpanId
	}
	return ""
}

func (x *AppTrace) GetXRequestId() string {
	if x != nil && x.XRequestId != nil {
		return *x.XRequestId
	}
	return ""
}

func (x *AppTrace) GetHttpProxyClient() string {
	if x != nil && x.HttpProxyClient != nil {
		return *x.HttpProxyClient
	}
	return ""
}

func (x *AppTrace) GetTraceIds() []string {
	if x != nil {
		return x.TraceIds
	}
	return nil
}

type KeyVal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val           string                 `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyVal) Reset() {
	*x = KeyVal{}
	mi := &file_WasmPluginApi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyVal) ProtoMessage() {}

func (x *KeyVal) ProtoReflect() protoreflect.Message {
	mi := &file_WasmPluginApi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyVal.ProtoReflect.Descriptor instead.
func (*KeyVal) Descriptor() ([]byte, []int) {
	return file_WasmPluginApi_proto_rawDescGZIP(), []int{3}
}

func (x *KeyVal) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyVal) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type AppInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ReqLen    *uint32                `protobuf:"varint,1,opt,name=req_len,json=reqLen,proto3,oneof" json:"req_len,omitempty"`
	RespLen   *uint32                `protobuf:"varint,2,opt,name=resp_len,json=respLen,proto3,oneof" json:"resp_len,omitempty"`
	RequestId *uint32                `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Info:
	//
	//	*AppInfo_Req
	//	*AppInfo_Resp
	Info        isAppInfo_Info `protobuf_oneof:"info"`
	Trace       *AppTrace      `protobuf:"bytes,12,opt,name=trace,proto3" json:"trace,omitempty"`
	ProtocolStr *string        `protobuf:"bytes,13,opt,name=protocol_str,json=protocolStr,proto3,oneof" json:"protocol_str,omitempty"`
	// a null `is_end` means no need for protocol merge
	IsEnd   *bool `protobuf:"varint,21,opt,name=is_end,json=isEnd,proto3,oneof" json:"is_end,omitempty"`
	IsAsync *bool `protobuf:"varint,22,opt,name=is_async,json=isAsync,proto3,oneof" json:"is_async,omitempty"`
	// L2 + L3 + L4 + TapSide
	IsReversed    *bool     `protobuf:"varint,23,opt,name=is_reversed,json=isReversed,proto3,oneof" json:"is_reversed,omitempty"`
	Attributes    []*KeyVal `protobuf:"bytes,31,rep,name=attributes,proto3" json:"attributes,omitempty"`
	BizType       *uint32   `protobuf:"varint,32,opt,name=biz_type,json=bizType,proto3,oneof" json:"biz_type,omitempty"`
	BizCode       *string   `protobuf:"bytes,33,opt,name=biz_code,json=bizCode,proto3,oneof" json:"biz_code,omitempty"`
	BizScenario   *string   `protobuf:"bytes,34,opt,name=biz_scenario,json=bizScenario,proto3,oneof" json:"biz_scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppInfo) Reset() {
	*x = AppInfo{}
	mi := &file_WasmPluginApi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppInfo) ProtoMessage() {}

func (x *AppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_WasmPluginApi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppInfo.ProtoReflect.Descriptor instead.
func (*AppInfo) Descriptor() ([]byte, []int) {
	return file_WasmPluginApi_proto_rawDescGZIP(), []int{4}
}

func (x *AppInfo) GetReqLen() uint32 {
	if x != nil && x.ReqLen != nil {
		return *x.ReqLen
	}
	return 0
}

func (x *AppInfo) GetRespLen() uint32 {
	if x != nil && x.RespLen != nil {
		return *x.RespLen
	}
	return 0
}

func (x *AppInfo) GetRequestId() uint32 {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return 0
}

func (x *AppInfo) GetInfo() isAppInfo_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *AppInfo) GetReq() *AppRequest {
	if x != nil {
		if x, ok := x.Info.(*AppInfo_Req); ok {
			return x.Req
		}
	}
	return nil
}

func (x *AppInfo) GetResp() *AppResponse {
	if x != nil {
		if x, ok := x.Info.(*AppInfo_Resp); ok {
			return x.Resp
		}
	}
	return nil
}

func (x *AppInfo) GetTrace() *AppTrace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *AppInfo) GetProtocolStr() string {
	if x != nil && x.ProtocolStr != nil {
		return *x.ProtocolStr
	}
	return ""
}

func (x *AppInfo) GetIsEnd() bool {
	if x != nil && x.IsEnd != nil {
		return *x.IsEnd
	}
	return false
}

func (x *AppInfo) GetIsAsync() bool {
	if x != nil && x.IsAsync != nil {
		return *x.IsAsync
	}
	return false
}

func (x *AppInfo) GetIsReversed() bool {
	if x != nil && x.IsReversed != nil {
		return *x.IsReversed
	}
	return false
}

func (x *AppInfo) GetAttributes() []*KeyVal {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *AppInfo) GetBizType() uint32 {
	if x != nil && x.BizType != nil {
		return *x.BizType
	}
	return 0
}

func (x *AppInfo) GetBizCode() string {
	if x != nil && x.BizCode != nil {
		return *x.BizCode
	}
	return ""
}

func (x *AppInfo) GetBizScenario() string {
	if x != nil && x.BizScenario != nil {
		return *x.BizScenario
	}
	return ""
}

type isAppInfo_Info interface {
	isAppInfo_Info()
}

type AppInfo_Req struct {
	Req *AppRequest `protobuf:"bytes,10,opt,name=req,proto3,oneof"`
}

type AppInfo_Resp struct {
	Resp *AppResponse `protobuf:"bytes,11,opt,name=resp,proto3,oneof"`
}

func (*AppInfo_Req) isAppInfo_Info() {}

func (*AppInfo_Resp) isAppInfo_Info() {}

type NatsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	ReplyTo       string                 `protobuf:"bytes,2,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NatsMessage) Reset() {
	*x = NatsMessage{}
	mi := &file_WasmPluginApi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NatsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatsMessage) ProtoMessage() {}

func (x *NatsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_WasmPluginApi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatsMessage.ProtoReflect.Descriptor instead.
func (*NatsMessage) Descriptor() ([]byte, []int) {
	return file_WasmPluginApi_proto_rawDescGZIP(), []int{5}
}

func (x *NatsMessage) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NatsMessage) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *NatsMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ZmtpMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Subscription:
	//
	//	*ZmtpMessage_MatchPattern
	Subscription  isZmtpMessage_Subscription `protobuf_oneof:"subscription"`
	Payload       []byte                     `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZmtpMessage) Reset() {
	*x = ZmtpMessage{}
	mi := &file_WasmPluginApi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZmtpMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZmtpMessage) ProtoMessage() {}

func (x *ZmtpMessage) ProtoReflect() protoreflect.Message {
	mi := &file_WasmPluginApi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZmtpMessage.ProtoReflect.Descriptor instead.
func (*ZmtpMessage) Descriptor() ([]byte, []int) {
	return file_WasmPluginApi_proto_rawDescGZIP(), []int{6}
}

func (x *ZmtpMessage) GetSubscription() isZmtpMessage_Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *ZmtpMessage) GetMatchPattern() string {
	if x != nil {
		if x, ok := x.Subscription.(*ZmtpMessage_MatchPattern); ok {
			return x.MatchPattern
		}
	}
	return ""
}

func (x *ZmtpMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type isZmtpMessage_Subscription interface {
	isZmtpMessage_Subscription()
}

type ZmtpMessage_MatchPattern struct {
	MatchPattern string `protobuf:"bytes,1,opt,name=match_pattern,json=matchPattern,proto3,oneof"`
}

func (*ZmtpMessage_MatchPattern) isZmtpMessage_Subscription() {}

var File_WasmPluginApi_proto protoreflect.FileDescriptor

const file_WasmPluginApi_proto_rawDesc = "" +
	"\n" +
	"\x13WasmPluginApi.proto\x12\vwasm_plugin\"\xdd\x01\n" +
	"\n" +
	"AppRequest\x12\x1d\n" +
	"\aversion\x18\x01 \x01(\tH\x00R\aversion\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x02 \x01(\tH\x01R\x04type\x88\x01\x01\x12\x1b\n" +
	"\x06domain\x18\x03 \x01(\tH\x02R\x06domain\x88\x01\x01\x12\x1f\n" +
	"\bresource\x18\x04 \x01(\tH\x03R\bresource\x88\x01\x01\x12\x1f\n" +
	"\bendpoint\x18\x05 \x01(\tH\x04R\bendpoint\x88\x01\x01B\n" +
	"\n" +
	"\b_versionB\a\n" +
	"\x05_typeB\t\n" +
	"\a_domainB\v\n" +
	"\t_resourceB\v\n" +
	"\t_endpoint\"\xcc\x01\n" +
	"\vAppResponse\x127\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.wasm_plugin.AppRespStatusH\x00R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x02 \x01(\x05H\x01R\x04code\x88\x01\x01\x12!\n" +
	"\texception\x18\x03 \x01(\tH\x02R\texception\x88\x01\x01\x12\x1b\n" +
	"\x06result\x18\x04 \x01(\tH\x03R\x06result\x88\x01\x01B\t\n" +
	"\a_statusB\a\n" +
	"\x05_codeB\f\n" +
	"\n" +
	"_exceptionB\t\n" +
	"\a_result\"\xbb\x02\n" +
	"\bAppTrace\x12\x1e\n" +
	"\btrace_id\x18\x01 \x01(\tH\x00R\atraceId\x88\x01\x01\x12\x1c\n" +
	"\aspan_id\x18\x02 \x01(\tH\x01R\x06spanId\x88\x01\x01\x12)\n" +
	"\x0eparent_span_id\x18\x03 \x01(\tH\x02R\fparentSpanId\x88\x01\x01\x12%\n" +
	"\fx_request_id\x18\x04 \x01(\tH\x03R\n" +
	"xRequestId\x88\x01\x01\x12/\n" +
	"\x11http_proxy_client\x18\x05 \x01(\tH\x04R\x0fhttpProxyClient\x88\x01\x01\x12\x1b\n" +
	"\ttrace_ids\x18\x06 \x03(\tR\btraceIdsB\v\n" +
	"\t_trace_idB\n" +
	"\n" +
	"\b_span_idB\x11\n" +
	"\x0f_parent_span_idB\x0f\n" +
	"\r_x_request_idB\x14\n" +
	"\x12_http_proxy_client\",\n" +
	"\x06KeyVal\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x10\n" +
	"\x03val\x18\x02 \x01(\tR\x03val\"\xb0\x05\n" +
	"\aAppInfo\x12\x1c\n" +
	"\areq_len\x18\x01 \x01(\rH\x01R\x06reqLen\x88\x01\x01\x12\x1e\n" +
	"\bresp_len\x18\x02 \x01(\rH\x02R\arespLen\x88\x01\x01\x12\"\n" +
	"\n" +
	"request_id\x18\x03 \x01(\rH\x03R\trequestId\x88\x01\x01\x12+\n" +
	"\x03req\x18\n" +
	" \x01(\v2\x17.wasm_plugin.AppRequestH\x00R\x03req\x12.\n" +
	"\x04resp\x18\v \x01(\v2\x18.wasm_plugin.AppResponseH\x00R\x04resp\x12+\n" +
	"\x05trace\x18\f \x01(\v2\x15.wasm_plugin.AppTraceR\x05trace\x12&\n" +
	"\fprotocol_str\x18\r \x01(\tH\x04R\vprotocolStr\x88\x01\x01\x12\x1a\n" +
	"\x06is_end\x18\x15 \x01(\bH\x05R\x05isEnd\x88\x01\x01\x12\x1e\n" +
	"\bis_async\x18\x16 \x01(\bH\x06R\aisAsync\x88\x01\x01\x12$\n" +
	"\vis_reversed\x18\x17 \x01(\bH\aR\n" +
	"isReversed\x88\x01\x01\x123\n" +
	"\n" +
	"attributes\x18\x1f \x03(\v2\x13.wasm_plugin.KeyValR\n" +
	"attributes\x12\x1e\n" +
	"\bbiz_type\x18  \x01(\rH\bR\abizType\x88\x01\x01\x12\x1e\n" +
	"\bbiz_code\x18! \x01(\tH\tR\abizCode\x88\x01\x01\x12&\n" +
	"\fbiz_scenario\x18\" \x01(\tH\n" +
	"R\vbizScenario\x88\x01\x01B\x06\n" +
	"\x04infoB\n" +
	"\n" +
	"\b_req_lenB\v\n" +
	"\t_resp_lenB\r\n" +
	"\v_request_idB\x0f\n" +
	"\r_protocol_strB\t\n" +
	"\a_is_endB\v\n" +
	"\t_is_asyncB\x0e\n" +
	"\f_is_reversedB\v\n" +
	"\t_biz_typeB\v\n" +
	"\t_biz_codeB\x0f\n" +
	"\r_biz_scenario\"\\\n" +
	"\vNatsMessage\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x19\n" +
	"\breply_to\x18\x02 \x01(\tR\areplyTo\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"^\n" +
	"\vZmtpMessage\x12%\n" +
	"\rmatch_pattern\x18\x01 \x01(\tH\x00R\fmatchPattern\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayloadB\x0e\n" +
	"\fsubscription*n\n" +
	"\rAppRespStatus\x12\v\n" +
	"\aRESP_OK\x10\x00\x12\x10\n" +
	"\fRESP_TIMEOUT\x10\x02\x12\x15\n" +
	"\x11RESP_SERVER_ERROR\x10\x03\x12\x15\n" +
	"\x11RESP_CLIENT_ERROR\x10\x04\x12\x10\n" +
	"\fRESP_UNKNOWN\x10\x05B\x06Z\x04.;pbb\x06proto3"

var (
	file_WasmPluginApi_proto_rawDescOnce sync.Once
	file_WasmPluginApi_proto_rawDescData []byte
)

func file_WasmPluginApi_proto_rawDescGZIP() []byte {
	file_WasmPluginApi_proto_rawDescOnce.Do(func() {
		file_WasmPluginApi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_WasmPluginApi_proto_rawDesc), len(file_WasmPluginApi_proto_rawDesc)))
	})
	return file_WasmPluginApi_proto_rawDescData
}

var file_WasmPluginApi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_WasmPluginApi_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_WasmPluginApi_proto_goTypes = []any{
	(AppRespStatus)(0),  // 0: wasm_plugin.AppRespStatus
	(*AppRequest)(nil),  // 1: wasm_plugin.AppRequest
	(*AppResponse)(nil), // 2: wasm_plugin.AppResponse
	(*AppTrace)(nil),    // 3: wasm_plugin.AppTrace
	(*KeyVal)(nil),      // 4: wasm_plugin.KeyVal
	(*AppInfo)(nil),     // 5: wasm_plugin.AppInfo
	(*NatsMessage)(nil), // 6: wasm_plugin.NatsMessage
	(*ZmtpMessage)(nil), // 7: wasm_plugin.ZmtpMessage
}
var file_WasmPluginApi_proto_depIdxs = []int32{
	0, // 0: wasm_plugin.AppResponse.status:type_name -> wasm_plugin.AppRespStatus
	1, // 1: wasm_plugin.AppInfo.req:type_name -> wasm_plugin.AppRequest
	2, // 2: wasm_plugin.AppInfo.resp:type_name -> wasm_plugin.AppResponse
	3, // 3: wasm_plugin.AppInfo.trace:type_name -> wasm_plugin.AppTrace
	4, // 4: wasm_plugin.AppInfo.attributes:type_name -> wasm_plugin.KeyVal
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_WasmPluginApi_proto_init() }
func file_WasmPluginApi_proto_init() {
	if File_WasmPluginApi_proto != nil {
		return
	}
	file_WasmPluginApi_proto_msgTypes[0].OneofWrappers = []any{}
	file_WasmPluginApi_proto_msgTypes[1].OneofWrappers = []any{}
	file_WasmPluginApi_proto_msgTypes[2].OneofWrappers = []any{}
	file_WasmPluginApi_proto_msgTypes[4].OneofWrappers = []any{
		(*AppInfo_Req)(nil),
		(*AppInfo_Resp)(nil),
	}
	file_WasmPluginApi_proto_msgTypes[6].OneofWrappers = []any{
		(*ZmtpMessage_MatchPattern)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_WasmPluginApi_proto_rawDesc), len(file_WasmPluginApi_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_WasmPluginApi_proto_goTypes,
		DependencyIndexes: file_WasmPluginApi_proto_depIdxs,
		EnumInfos:         file_WasmPluginApi_proto_enumTypes,
		MessageInfos:      file_WasmPluginApi_proto_msgTypes,
	}.Build()
	File_WasmPluginApi_proto = out.File
	file_WasmPluginApi_proto_goTypes = nil
	file_WasmPluginApi_proto_depIdxs = nil
}
