package main

const tFile = `// This code was autogenerated from {{.GetName}}, do not edit.

package {{.GetPackage}}

import (
	"encoding/json"
)

func ProtobufToJson(service string, method string, isRequest bool, data []byte) []byte {
	switch service {
{{- range .Service}}
{{- $serviceName := .GetName}}
		case "{{$serviceName}}":
			switch method {
{{- range .Method}}
{{- $methodName := .GetName}}
				case "{{$methodName}}":
					if isRequest {
						var obj {{GoType .GetInputType}}
						obj.UnmarshalVT(data)
						data, err := json.Marshal(obj)
						if err != nil {
							return nil
						}
						return data
					} else {
						var obj {{GoType .GetOutputType}}
						obj.UnmarshalVT(data)
						data, err := json.Marshal(obj)
						if err != nil {
							return nil
						}
						return data
					}
{{- end}}
			}
{{- end}}
	}
	return nil
}
`
